language: go
go:
- 1.11.x

git:
  depth: false

env:
  - GO111MODULE=on

install:
  - go get github.com/mattn/goveralls

#  - go get -u honnef.co/go/tools/cmd/megacheck
#  - go get -u github.com/client9/misspell/cmd/misspell

before_script:
- EXCLUDE_VENDOR=$(go list ./... | grep -v "/vendor/")
- go build
- $(exit $(go fmt $EXCLUDE_VENDOR | wc -l))
- go vet $EXCLUDE_VENDOR
#- misspell -erruor -locale US .
#- megacheck $EXCLUDE_VENDOR

script:
- ./scripts/cov.sh TRAVIS

after_success:
- go clean
- git reset --hard

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
